site_name: 'Excel project docs'

theme:
  name: "material"

plugins:
  - mkdocstrings

markdown_extensions:
  - def_list

nav:
  - Home: index.md
  - Preprocessing: preprocessing.md
  -  Dashboard: dashboard.md
